 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.vendasnb.view;

import br.com.vendasnb.controller.ControllerCargo;
import br.com.vendasnb.model.ModelCargo;
import br.com.vendasnb.util.Formatador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.TableView;

/**
 *
 * @author Nicolas
 */
public class ViewCargo extends javax.swing.JFrame {
    
    ArrayList<ModelCargo> listaModelCargo = new ArrayList<>();
    ModelCargo modelCargo = new ModelCargo();
    ControllerCargo controllerCargo = new ControllerCargo();
    Formatador formatador = new Formatador();
    String salvarAlterar;
    

    /**
     * Creates new form ViewCargo
     */
    public ViewCargo() {
        initComponents();
        this.carregarCargo();
        setLocationRelativeTo(null);
        this.habilitarDesabilitar(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCarCodigo = new javax.swing.JTextField();
        txtCarDesc = new javax.swing.JTextField();
        txtCarPesquisa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCargo = new javax.swing.JTable();
        btnCarCancelar = new javax.swing.JButton();
        btnCarEditar = new javax.swing.JButton();
        btnCarNew = new javax.swing.JButton();
        btnCarSalvar = new javax.swing.JButton();
        btnCarDeletar = new javax.swing.JButton();
        txtCarSalario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cargo");
        setResizable(false);

        jLabel1.setText("Código:");

        jLabel2.setText("Descrição: ");

        jLabel3.setText("Sálario: ");

        txtCarCodigo.setEnabled(false);

        jLabel4.setText("Pesquisar:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vendasnb/imagens/pesquisar.png"))); // NOI18N
        jButton1.setToolTipText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tableCargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Descriçao", "Salario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCargo);

        btnCarCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vendasnb/imagens/cancelar.png"))); // NOI18N
        btnCarCancelar.setToolTipText("Cancelar");
        btnCarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarCancelarActionPerformed(evt);
            }
        });

        btnCarEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vendasnb/imagens/editar.png"))); // NOI18N
        btnCarEditar.setToolTipText("Editar");
        btnCarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarEditarActionPerformed(evt);
            }
        });

        btnCarNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vendasnb/imagens/novo.png"))); // NOI18N
        btnCarNew.setToolTipText("Novo");
        btnCarNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarNewActionPerformed(evt);
            }
        });

        btnCarSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vendasnb/imagens/salvar.png"))); // NOI18N
        btnCarSalvar.setToolTipText("Salvar");
        btnCarSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarSalvarActionPerformed(evt);
            }
        });

        btnCarDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vendasnb/imagens/deletar.png"))); // NOI18N
        btnCarDeletar.setToolTipText("Deletar");
        btnCarDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarDeletarActionPerformed(evt);
            }
        });

        txtCarSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCarSalarioFocusLost(evt);
            }
        });
        txtCarSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCarSalarioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtCarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCarDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCarPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnCarCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCarDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCarSalvar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCarPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jButton1))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarDeletar)
                    .addComponent(btnCarSalvar)
                    .addComponent(btnCarNew)
                    .addComponent(btnCarEditar)
                    .addComponent(btnCarCancelar))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarCancelarActionPerformed
        // Cancelar
        this.habilitarDesabilitar(false);
        this.limparCampo();
    }//GEN-LAST:event_btnCarCancelarActionPerformed

    private void btnCarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarEditarActionPerformed
        // Editar
        salvarAlterar = "alterar";
         habilitarDesabilitar(true);
        int linha = tableCargo.getSelectedRow();
        try {
            int codigoCargo = (int) tableCargo.getValueAt(linha, 0);
            // recuperar os dados do banco
            modelCargo = controllerCargo.retornaCargoController(codigoCargo);
            // setar na interface
            this.txtCarCodigo.setText(String.valueOf(modelCargo.getIdCargo()));
            this.txtCarDesc.setText(modelCargo.getDescricao());
            this.txtCarSalario.setText(String.valueOf(modelCargo.getSalario()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado!", "AVISO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCarEditarActionPerformed

    private void btnCarSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarSalvarActionPerformed
        // TODO add your handling code here:
        if(salvarAlterar.equals("salvar")){
           this.salvarCargo();
        }else if (salvarAlterar.equals("alterar")){
            this.alterarCargo();
        }
    }//GEN-LAST:event_btnCarSalvarActionPerformed

    private void btnCarNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarNewActionPerformed
        // novo
        habilitarDesabilitar(true);
        salvarAlterar = "salvar";
    }//GEN-LAST:event_btnCarNewActionPerformed

    private void btnCarDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarDeletarActionPerformed
        // deletar
        int linha = tableCargo.getSelectedRow();
        int codigoCargo = (int) tableCargo.getValueAt(linha, 0);

        if (controllerCargo.excluirCargoController(codigoCargo)) {
            JOptionPane.showMessageDialog(this, "Fornecedor excluído com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            this.carregarCargo();
            this.habilitarDesabilitar(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir o Fornecedor!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCarDeletarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // pesquisar
        DefaultTableModel modelo = (DefaultTableModel) this.tableCargo.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.tableCargo.setRowSorter(classificador);
        
        String texto = txtCarPesquisa.getText();
        classificador.setRowFilter(RowFilter.regexFilter(texto,1));  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCarSalarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarSalarioKeyReleased

        
    }//GEN-LAST:event_txtCarSalarioKeyReleased

    private void txtCarSalarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCarSalarioFocusLost
        // Conversao de virgula
        txtCarSalario.setText(String.valueOf(new Formatador().converterVirgulaParaPonto(txtCarSalario.getText()))) ;
    }//GEN-LAST:event_txtCarSalarioFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCargo().setVisible(true);
            }
        });
    }
    
    public void carregarCargo(){
        listaModelCargo = controllerCargo.retornaListaCargoController();
        DefaultTableModel modelo = (DefaultTableModel) this.tableCargo.getModel();
        modelo.setNumRows(0);
        // inserir dados na tabela
        for(int i=0; i < listaModelCargo.size(); i++){
            modelo.addRow(new Object[]{
                listaModelCargo.get(i).getIdCargo(),
                listaModelCargo.get(i).getDescricao(),
                listaModelCargo.get(i).getSalario()
            });
        }
    }
    
    public void habilitarDesabilitar(boolean condicao){
        txtCarDesc.setEnabled(condicao);
        txtCarSalario.setEnabled(condicao);
    }
    
    public void limparCampo(){
        txtCarCodigo.setText("");
        txtCarDesc.setText("");
        txtCarSalario.setText("");
    }
    
    /***
     * Salva os fornecedores no banco
     */
    
    
    private void salvarCargo() {
        try {
            modelCargo.setDescricao(this.txtCarDesc.getText());
            modelCargo.setSalario(formatador.converterVirgulaParaPonto(this.txtCarSalario.getText()));

            if (controllerCargo.salvarCargoController(modelCargo) > 0) {
                JOptionPane.showMessageDialog(this, "Cargo cadastrado com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                this.carregarCargo();
                this.limparCampo();
                this.habilitarDesabilitar(false);
            }else {
               JOptionPane.showMessageDialog(this, "Erro ao cadastrar o Cargo!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }catch (Exception e) {
           // JOptionPane.showMessageDialog(this, "Erro ao cadastrar o Cargo!", "ERRO", JOptionPane.ERROR_MESSAGE);
           e.printStackTrace();
        }
    }
    
    /***
     * Altera os fornecedores no banco
     */
    private void alterarCargo(){
        try {
            modelCargo.setDescricao(txtCarDesc.getText());
            modelCargo.setSalario(formatador.converterVirgulaParaPonto(txtCarSalario.getText()));
            
            if(controllerCargo.alteraCargoController(modelCargo)){
                JOptionPane.showMessageDialog(this, "Cargo alterado com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                this.carregarCargo();
                this.limparCampo();
                habilitarDesabilitar(false);
            }else {
               JOptionPane.showMessageDialog(this, "Erro ao alterar o cargo!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao alterar o cargo!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarCancelar;
    private javax.swing.JButton btnCarDeletar;
    private javax.swing.JButton btnCarEditar;
    private javax.swing.JButton btnCarNew;
    private javax.swing.JButton btnCarSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCargo;
    private javax.swing.JTextField txtCarCodigo;
    private javax.swing.JTextField txtCarDesc;
    private javax.swing.JTextField txtCarPesquisa;
    private javax.swing.JTextField txtCarSalario;
    // End of variables declaration//GEN-END:variables
}
